name: HelloWorldJNI
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
    build:
        name: Build stage
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v1
          - name: Build HelloWorldJNI
            run: |
              ./HelloWorldJNI/build.sh
